dependencies:
  - conda-forge::pip
  - conda-forge::python=3.9
  - pip:
      - matplotlib==3.6.3
      - numpy==1.24.2
      - astropy==5.2.1
      - jupyterlab==3.6.1
      - ipywidgets==8.0.4
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - tqdm==4.64.1
      - nbconvert==7.2.10
